### ISSUE TITLE
Add cryptography details

### ISSUE THREAD

**Issue by GraDKh** [eqlabs/polkadot-light-client-spec#5]
Fix concern: 
> Missing a clear comparison of required components between Light-Client and Full Node. Ideally describe a spectrum of functionalities that a light-client can support.

**Comment by kylegranger** [comment]
My strategy here is to lean on what Polkadot itself says about Substrate Connect
https://wiki.polkadot.network/docs/build-substrate

**Comment by kylegranger** [comment]
This is completed.  Closing.
